#!/bin/sh

# WHAT?
# turns off half of the cores

# WHY?
# to test out AMD-FX performance, when no threads can share one floating point operator
# check out Clustered Multi-Threading (CMT)
# https://en.wikipedia.org/wiki/Bulldozer_(microarchitecture)


# thanks to Anonymous at http://pundiramit.blogspot.fi/2010/07/how-to-disable-cpu-cores-in-multicore.html

fullcores=$(cat /sys/devices/system/cpu/cpu1/online)

for i in /sys/devices/system/cpu/cpu{1,3,5,7}/online
do 
    if [ $fullcores -eq 1 ]
    then
        echo 0 > $i
        echo "half cores disabled"
    else
        echo "all cores enabled"
        echo 1 > $i
    fi
done
